# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: "/calculator"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels:
      - "calculator"
      - "dependencies"

  - directory: "/chat"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels:
      - "chat"
      - "dependencies"

  # - directory: "/chess"
  #   package-ecosystem: "npm"
  #   schedule:
  #     interval: "weekly"
  #   labels:
  #     - "chess"
  #     - "dependencies" 

  - directory: "/election"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels:
      - "election"
      - "dependencies"

  - directory: "/hello-dotnet"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
    labels:
      - "hello-dotnet"
      - "dependencies"

  - directory: "/mongo-music"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
    labels:
      - "mongo-music"
      - "dependencies"

  - directory: "/ocr"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels:
      - "ocr"
      - "dependencies"    

  - directory: "/printer"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels:
      - "printer"
      - "dependencies"    

  - directory: "/qrcode"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels:
      - "qrcode"
      - "dependencies"    

  - directory: "/qrcode-multi-lang/packages/default/qr"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels:
      - "qrcode-multi-lang-js"
      - "dependencies"         

  - directory: "/qrcode-multi-lang/packages/default/qr-java"
    package-ecosystem: "gradle"
    schedule:
      interval: "weekly"
    labels:
      - "qrcode-multi-lang-java"
      - "dependencies"         

  - directory: "/trade"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels:
      - "trade"
      - "dependencies"   

  - directory: "/visits"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    labels:
      - "visits"
      - "dependencies"         
      
  # GITHUB ACTIONS external action updates
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
